const dotenv = require('dotenv');
dotenv.config();

module.exports = {
    MUMBAI_ENDPOINT: process.env.MUMBAI_ENDPOINT,
    MAINNET_ENDPOINT: process.env.MAINNET_ENDPOINT,
    MONGO_USER_DB_CONN_STRING: process.env.MONGO_USER_DB_CONN_STRING,
    MONGO_TRANSACTION_DB_CONN_STRING: process.env.MONGO_TRANSACTION_DB_CONN_STRING,
    MONGO_USER_INFO_COLLECTION: process.env.MONGO_USER_INFO_COLLECTION,
    MONGO_TRANSACTION_COLLECTION: process.env.MONGO_TRANSACTION_COLLECTION
}
